# Generated by Django 4.2.13 on 2024-05-11 21:19

import app.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', app.manager.CustomUserManager()),
            ],
        ),
    ]
