# Generated by Django 4.2.13 on 2024-05-12 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
